### ISSUE TITLE
panic: runtime error: index out of range [3] with length 0  goroutine 7639 [running]: encoding/binary.bigEndian.Uint32(...)         /usr/lib/golang/src/encoding/binary/binary.go:112

### ISSUE THREAD

**Issue by xianchuhan** [gwuhaolin/livego#186]
微信小程序推流崩溃到func (conn *Conn) handleControlMsg(c *ChunkStream) {
	if c.TypeID == idSetChunkSize {
		conn.remoteChunkSize = binary.BigEndian.Uint32(c.Data)
	} else if c.TypeID == idWindowAckSize {
		conn.remoteWindowAckSize = binary.BigEndian.Uint32(c.Data)
	}
}

**Comment by matthewgao** [comment]
Needs more information to determine the root cause of the issue, or any reproduce step?

**Comment by xianchuhan** [comment]
Until&nbsp;this&nbsp;problem&nbsp;is that&nbsp;they&nbsp;are&nbsp;accurate,&nbsp;described&nbsp;again&nbsp;again,&nbsp;micro -&nbsp;applet&nbsp;live-pusher&nbsp;the&nbsp;letter&nbsp;just&nbsp;push&nbsp;the&nbsp;audio&nbsp;stream,chunksize&nbsp;declared&nbsp;letter&nbsp;small&nbsp;program&nbsp;size&nbsp;is&nbsp;256,&nbsp;but&nbsp;the&nbsp;actual&nbsp;individual&nbsp;bag&nbsp;will&nbsp;send&nbsp;audio&nbsp;packet&nbsp;is greater than&nbsp;256,livego&nbsp;should&nbsp;be&nbsp;to&nbsp;address&nbsp;this&nbsp;exception&nbsp;is not&nbsp;handled,&nbsp;leading to&nbsp;livego&nbsp;crash.
A&nbsp;similar&nbsp;issue&nbsp;with&nbsp;micro -&nbsp;letter&nbsp;community&nbsp;linked&nbsp;below:


https://developers.weixin.qq.com/community/develop/doc/0002c84103c080f71e7c901af5ac00





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gwuhaolin/livego"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月8日(星期五) 晚上11:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gwuhaolin/livego] panic: runtime error: index out of range [3] with length 0  goroutine 7639 [running]: encoding/binary.bigEndian.Uint32(...)         /usr/lib/golang/src/encoding/binary/binary.go:112 (#186)





 
Needs more information to determine the root cause of the issue, or any reproduce step?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xianchuhan** [comment]
Until this problem is that they are accurate, described again again, micro - applet live-pusher the letter just push the audio stream,chunksize declared letter small program size is 256, but the actual individual bag will send audio packet is greater than 256,livego should be to address this exception is not handled, leading to livego crash.
A similar issue with micro - letter community linked below:
https://developers.weixin.qq.com/community/develop/doc/0002c84103c080f71e7c901af5ac00
