### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by XiexieYang** [gwuhaolin/livego#195]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x504e4c]

goroutine 39 [running]:
bufio.(*Writer).Flush(0xc00021a300, 0xc002a3045c, 0x7f1)
        /opt/hostedtoolcache/go/1.14.13/x64/src/bufio/bufio.go:591 +0x5c
bufio.(*Writer).Write(0xc00021a300, 0xc002a3045c, 0x6490, 0x5aba4, 0xb, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.14.13/x64/src/bufio/bufio.go:627 +0xfa
net/http.(*response).write(0xc00022c380, 0x6490, 0xc002a3045c, 0x6490, 0x5aba4, 0x0, 0x0, 0xb, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.14.13/x64/src/net/http/server.go:1606 +0x315
net/http.(*response).Write(0xc00022c380, 0xc002a3045c, 0x6490, 0x5aba4, 0xb, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.14.13/x64/src/net/http/server.go:1564 +0x56
github.com/gwuhaolin/livego/protocol/httpflv.(*FLVWriter).SendPacket(0xc000268000, 0x0, 0x0)
        /home/runner/work/livego/livego/protocol/httpflv/writer.go:151 +0x191
github.com/gwuhaolin/livego/protocol/httpflv.NewFLVWriter.func1(0xc000268000)
        /home/runner/work/livego/livego/protocol/httpflv/writer.go:55 +0x2f
created by github.com/gwuhaolin/livego/protocol/httpflv.NewFLVWriter
        /home/runner/work/livego/livego/protocol/httpflv/writer.go:54 +0x36f

**Comment by q191201771** [comment]
推荐另一个同类型的Go流媒体项目，感兴趣可以看看：
https://github.com/q191201771/lal

**Comment by zsddyd** [comment]
看起来好像没人维护了。。。
